### PR TITLE
Test change

### PR DESCRIPTION
**Pull request by epiclulz221**
test this please

HOST_OSES=ALL
BUILD_TOOLCHAINS=IAR,GCC_ARM
TEST_PLATFORMS=K64F,NRF51822

### CODE REVIEW

**Comment by epiclulz221** [comment]
test this please

HOST_OSES=ALL
BUILD_TOOLCHAINS=IAR,GCC_ARM
TEST_PLATFORMS=K64F,NRF51822

**Comment by bridadan** [comment]
test this please

HOST_OSES=ALL
BUILD_TOOLCHAINS=IAR,GCC_ARM
TEST_PLATFORMS=K64F,NRF51822

**Comment by bridadan** [comment]
test this please

HOST_OSES=ALL
BUILD_TOOLCHAINS=IAR,GCC_ARM
TEST_PLATFORMS=K64F,NRF51822

**Comment by bridadan** [comment]
test this please

HOST_OSES=ALL
BUILD_TOOLCHAINS=IAR,GCC_ARM
TEST_PLATFORMS=K64F,NRF51822

**Comment by bridadan** [comment]
test this please

HOST_OSES=ALL
BUILD_TOOLCHAINS=IAR,GCC_ARM
TEST_PLATFORMS=K64F,NRF51822

**Comment by bridadan** [comment]
test this please

HOST_OSES=ALL
BUILD_TOOLCHAINS=IAR,GCC_ARM
TEST_PLATFORMS=K64F,NRF51822

**Comment by bridadan** [comment]
HOST_OSES=linux,windows
BUILD_TOOLCHAINS=IAR,GCC_ARM
TEST_PLATFORMS=K64F,NRF51822

**Comment by bridadan** [comment]
test this please

HOST_OSES=linux,windows
BUILD_TOOLCHAINS=IAR,GCC_ARM
TEST_PLATFORMS=K64F,NRF51822

**Comment by bridadan** [comment]
test this please

HOST_OSES=ALL
BUILD_TOOLCHAINS=IAR,GCC_ARM
TEST_PLATFORMS=K64F,LPC1768

**Comment by bridadan** [comment]
test this please

HOST_OSES=ALL
BUILD_TOOLCHAINS=IAR,GCC_ARM
TEST_PLATFORMS=K64F,LPC1768

**Comment by bridadan** [comment]
test this please

HOST_OSES=ALL
BUILD_TOOLCHAINS=IAR,GCC_ARM
TEST_PLATFORMS=K64F,LPC1768

**Comment by bridadan** [comment]
test this please

HOST_OSES=ALL
BUILD_TOOLCHAINS=IAR,GCC_ARM
TEST_PLATFORMS=K64F,LPC1768

**Comment by bridadan** [comment]
test this please

HOST_OSES=windows
BUILD_TOOLCHAINS=GCC_ARM
TEST_PLATFORMS=K64F,LPC1768

**Comment by bridadan** [comment]
test this please

HOST_OSES=linux
BUILD_TOOLCHAINS=ALL
TEST_PLATFORMS=ALL

**Comment by bridadan** [comment]
test this please

HOST_OSES=ALL
BUILD_TOOLCHAINS=GCC_ARM
TEST_PLATFORMS=K64F

**Comment by bridadan** [comment]
test this please

HOST_OSES=ALL
BUILD_TOOLCHAINS=GCC_ARM
TARGETS=K64F

**Comment by bridadan** [comment]
test this please

HOST_OSES=ALL
BUILD_TOOLCHAINS=GCC_ARM
TARGETS=K64F

**Pull request closed without merging**
